import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { Issue, Task, TaskWorkspace } from './domain/contracts';
import { getTaskActionState, getWorkflowStepIndex, taskStatusLabels, workflowSteps } from './domain/workflow';
import { taskRepository } from './data/repositoryFactory';

const demoId = 'task-demo';
const formatTime = (value: string) => new Intl.DateTimeFormat('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
const errors = (issues: Issue[]) => issues.filter((issue) => issue.severity === 'error' && !issue.resolved).length;

function StatusPill({ status }: { status: Task['status'] }) { return <span className={`status status-${status.toLowerCase()}`}>{taskStatusLabels[status]}</span>; }
function Shell({ title, eyebrow, children, action }: { title: string; eyebrow: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <div className="app-shell"><aside className="sidebar"><Link className="brand" to="/tasks"><span>EA</span><b>上新工作台</b></Link><nav><Link to="/tasks">任务中心</Link><Link to={`/tasks/${demoId}/products`}>审核工作台</Link><Link to={`/tasks/${demoId}/audit`}>审核记录</Link></nav><div className="sidebar-foot">MVP · 前端演示<br /><small>数据来自本地 Mock 适配器</small></div></aside><main className="workspace"><header className="topbar"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</header>{children}</main></div>;
}
function Stepper({ workspace }: { workspace: TaskWorkspace }) { const current = getWorkflowStepIndex(workspace.task.status); return <ol className="stepper">{workflowSteps.map((step, index) => <li key={step.status} className={index <= current ? 'complete' : ''}><i>{index + 1}</i><span>{step.label}</span></li>)}</ol>; }
function IssuePanel({ issues }: { issues: Issue[] }) { const open = issues.filter((issue) => !issue.resolved); return <section className="panel issue-panel"><div className="panel-title"><div><p className="eyebrow">数据质量</p><h2>待处理问题</h2></div><strong>{open.length}</strong></div>{open.length === 0 ? <p className="empty">没有未处理问题，可以继续审核。</p> : <div className="issue-list">{open.map((issue) => <article key={issue.id} className={`issue ${issue.severity}`}><span>{issue.severity === 'error' ? '错误' : issue.severity === 'warning' ? '提醒' : '提示'}</span><div><b>{issue.message}</b><small>{issue.source_ref} · {issue.field}</small></div></article>)}</div>}<p className="muted">请修正对应商品或 SKU 事实；后端重新检测后会更新问题状态。</p></section>; }
function useWorkspace() { const { taskId = demoId } = useParams(); const [workspace, setWorkspace] = useState<TaskWorkspace | null>(null); const [message, setMessage] = useState(''); const load = async () => { const result = await taskRepository.getWorkspace(taskId); if (result.data) setWorkspace({ ...result.data }); }; useEffect(() => { void load(); }, [taskId]); return { taskId, workspace, setWorkspace, message, setMessage, reload: load }; }

export function TaskListPage() { const [tasks, setTasks] = useState<Task[]>([]); useEffect(() => { void taskRepository.listTasks().then((result) => setTasks(result.data ?? [])); }, []); return <Shell eyebrow="任务中心" title="商品上新任务" action={<Link className="primary-button" to="/tasks/new">新建任务</Link>}><section className="hero-card"><div><p className="eyebrow">从 Excel 到可导出商品资料</p><h2>每一步都有明确的审核边界</h2><p>解析、商品确认和文案确认分层进行；系统只提供建议，最终发布由人工完成。</p></div><Link className="soft-button" to={`/tasks/${demoId}/products`}>打开演示工作台</Link></section><section className="panel table-panel"><div className="panel-title"><div><p className="eyebrow">全部任务</p><h2>进行中的工作</h2></div><span>{tasks.length} 个任务</span></div><div className="task-table"><div className="table-head"><span>任务</span><span>状态</span><span>阻塞项</span><span>下一步</span></div>{tasks.map((task) => { const action = getTaskActionState({ status: task.status, unresolvedErrorCount: task.id === demoId ? 2 : 0, taskId: task.id }); return <div className="table-row" key={task.id}><div><b>{task.task_name}</b><small>{task.category} · {formatTime(task.updated_at)}</small></div><StatusPill status={task.status} /><span className={task.id === demoId ? 'issue-count' : ''}>{task.id === demoId ? '2 个错误待处理' : '—'}</span><Link className={action.disabled ? 'disabled-link' : 'text-link'} to={action.href}>{action.label} →</Link></div>; })}</div></section></Shell>; }

export function NewTaskPage() { const nav = useNavigate(); const [name, setName] = useState(''); const [category, setCategory] = useState('服饰'); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return setError('请填写任务名称'); const result = await taskRepository.createTask({ task_name: name.trim(), category }); if (result.data) nav(`/tasks/${result.data.id}/upload`); }; return <Shell eyebrow="创建任务" title="开始一批新的上新资料"><section className="form-card"><p>创建后先上传固定 Excel 模板。当前为前端 Mock 演示，不会写入真实业务数据。</p><form onSubmit={submit}><label>任务名称<input value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：夏季基础款短袖上新" /></label><label>商品类目<select value={category} onChange={(e) => setCategory(e.target.value)}><option>服饰</option><option>家居</option><option>美妆</option><option>食品</option></select></label>{error && <p className="form-error">{error}</p>}<button className="primary-button" type="submit">创建并上传文件</button></form></section></Shell>; }

export function UploadPage() { const { taskId, workspace, setWorkspace, message } = useWorkspace(); const [file, setFile] = useState<File | null>(null); const upload = async () => { if (!file) return; const result = await taskRepository.uploadSource(taskId, file); if (result.data) setWorkspace({ ...result.data }); else alert(result.error?.message); }; const parse = async () => { const result = await taskRepository.startParse(taskId); if (result.data) setWorkspace({ ...result.data }); }; if (!workspace) return <LoadingPage />; return <Shell eyebrow="文件上传" title={workspace.task.task_name}><section className="split-grid"><div className="panel upload-card"><p className="eyebrow">步骤 1 / 6</p><h2>上传 Excel 源文件</h2><p>仅支持 `.xlsx`。文件会在服务端解析、标准化并生成问题清单。</p><label className="file-drop">选择文件<input type="file" accept=".xlsx" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /><b>{file?.name || '选择 .xlsx 文件'}</b></label><button className="primary-button" onClick={upload} disabled={!file || workspace.task.status !== 'DRAFT'}>上传源文件</button>{workspace.task.status === 'UPLOADED' && <button className="soft-button" onClick={parse}>开始解析</button>}<p className="muted">{message}</p></div><section className="panel"><p className="eyebrow">当前状态</p><StatusPill status={workspace.task.status} /><Stepper workspace={workspace} /></section></section></Shell>; }

export function ProcessingPage() { const { workspace } = useWorkspace(); if (!workspace) return <LoadingPage />; const action = getTaskActionState({ status: workspace.task.status, unresolvedErrorCount: errors(workspace.issues), taskId: workspace.task.id }); return <Shell eyebrow="处理进度" title="解析与标准化"><section className="progress-card"><div className="orbit">✓</div><p className="eyebrow">当前状态</p><h2>{taskStatusLabels[workspace.task.status]}</h2><p>Mock 演示会在提交解析后直接进入商品审核；真实进度将由后端状态机驱动。</p><Link className="primary-button" to={action.href}>{action.label}</Link></section><Stepper workspace={workspace} /></Shell>; }

export function ProductReviewPage() { const { taskId, workspace, setWorkspace, message, setMessage } = useWorkspace(); const approve = async () => { const result = await taskRepository.approveProducts(taskId); if (result.data) { setWorkspace({ ...result.data }); setMessage('商品审核已通过，请生成文案后进行审核。'); } else setMessage(result.error?.message ?? '暂时不能审核'); }; if (!workspace) return <LoadingPage />; const openErrors = errors(workspace.issues); return <Shell eyebrow="审核工作台" title={workspace.task.task_name} action={<StatusPill status={workspace.task.status} />}><Stepper workspace={workspace}/><div className="review-grid"><section className="panel product-card"><div className="panel-title"><div><p className="eyebrow">商品事实</p><h2>{workspace.products[0]?.product_name ?? '等待解析结果'}</h2></div><span>{workspace.products.length} 个商品</span></div><dl><div><dt>类目</dt><dd>{workspace.products[0]?.category}</dd></div><div><dt>材质</dt><dd>{workspace.products[0]?.material}</dd></div><div><dt>来源</dt><dd>Excel 第 {workspace.products[0]?.source_row} 行</dd></div></dl><h3>SKU 明细</h3><div className="sku-table">{workspace.skus.map((sku) => <div key={sku.id}><b>{sku.sku_code}</b><span>{sku.color ?? '待补颜色'} · {sku.size ?? '—'}</span><span>{sku.price ? `¥${sku.price}` : '待补价格'}</span><span>{sku.stock ?? '待补库存'}</span></div>)}</div><div className="review-action"><div><b>{openErrors ? `还有 ${openErrors} 个错误需要处理` : '数据已满足审核条件'}</b><small>{message || '审核通过后才可以生成和审核文案。'}</small></div><button className="primary-button" disabled={openErrors > 0 || workspace.task.status !== 'WAITING_PRODUCT_REVIEW'} onClick={approve}>审核商品通过</button></div></section><IssuePanel issues={workspace.issues}/></div></Shell>; }

export function CopyReviewPage() { const { taskId, workspace, setWorkspace, message, setMessage } = useWorkspace(); const generate = async () => { const result = await taskRepository.generateCopy(taskId); if (result.data) { setWorkspace({ ...result.data }); setMessage('文案已生成，等待人工审核。'); } else setMessage(result.error?.message ?? '暂时不能生成文案'); }; const approve = async () => { const result = await taskRepository.approveCopy(taskId); if (result.data) { setWorkspace({ ...result.data }); setMessage('文案审核已通过，可以导出。'); } else setMessage(result.error?.message ?? '暂时不能审核'); }; if (!workspace) return <LoadingPage />; const content = workspace.generated_content[0]; const allowed = workspace.task.status === 'WAITING_COPY_REVIEW'; const canGenerate = workspace.task.status === 'PRODUCT_APPROVED'; return <Shell eyebrow="文案审核" title="确认商品表达"><Stepper workspace={workspace}/><div className="review-grid"><section className="panel copy-card"><p className="eyebrow">AI 生成建议 · 需要人工确认</p><h2>{content?.title ?? '尚未生成文案'}</h2><h3>卖点建议</h3><ul>{content?.selling_points.map((point) => <li key={point}>{point}</li>)}</ul><div className="claim-box"><b>待确认表述</b>{content?.unsupported_claims.map((claim) => <span key={claim}>{claim}</span>)}</div><div className="review-action"><div><b>{allowed ? '可以进行文案审核' : canGenerate ? '商品已确认，可以生成文案' : '等待商品审核完成'}</b><small>{message || '文案不会自动视为商品事实。'}</small></div>{canGenerate && <button className="soft-button" onClick={generate}>生成商品文案</button>}<button className="primary-button" disabled={!allowed} onClick={approve}>审核文案通过</button></div></section><IssuePanel issues={workspace.issues}/></div></Shell>; }

export function ExportPage() { const { taskId, workspace, setWorkspace, message, setMessage } = useWorkspace(); const doExport = async () => { const result = await taskRepository.exportTask(taskId); if (result.data) { setWorkspace({ ...result.data }); setMessage('已生成可下载的演示文件。'); } else setMessage(result.error?.message ?? '暂时不能导出'); }; if (!workspace) return <LoadingPage />; const exported = workspace.task.status === 'EXPORTED'; return <Shell eyebrow="导出结果" title="准备交付上新资料"><section className="export-card"><div className="export-icon">↓</div><p className="eyebrow">最终交付</p><h2>{exported ? '上新文件已生成' : '等待审核完成'}</h2><p>{message || (exported ? '本地 Mock 演示中可下载导出结果。' : '商品和文案均审核通过后，才会开放导出。')}</p>{exported ? <a className="primary-button" href="data:text/plain;charset=utf-8,Mock%20export%20ready" download="电商上新结果.xlsx">下载导出结果</a> : <button className="primary-button" disabled onClick={doExport}>导出上新文件</button>}{workspace.task.status === 'APPROVED' && <button className="soft-button" onClick={doExport}>生成上新文件</button>}</section></Shell>; }

export function AuditPage() { const { workspace } = useWorkspace(); if (!workspace) return <LoadingPage />; return <Shell eyebrow="审核记录" title="每一次决策都可追溯"><section className="panel audit-card"><div className="panel-title"><div><p className="eyebrow">任务历史</p><h2>{workspace.task.task_name}</h2></div><Link className="text-link" to={`/tasks/${workspace.task.id}/products`}>返回审核工作台 →</Link></div><div className="timeline">{workspace.audit_events.map((event) => <article key={event.id}><i></i><div><small>{formatTime(event.created_at)} · {event.source}</small><h3>{event.event}</h3><p>{event.detail}</p></div><b>{event.actor}</b></article>)}</div></section></Shell>; }
export function LoginPage() { return <Shell eyebrow="访问控制" title="登录将在后续迭代接入"><section className="panel"><p>当前 MVP 不处理真实身份认证，也不会在前端保存任何密钥。</p></section></Shell>; }
export function NotFoundPage() { return <Shell eyebrow="404" title="页面不存在" action={<Link className="primary-button" to="/tasks">返回任务中心</Link>}><section className="panel"><p>请从任务中心重新进入工作流。</p></section></Shell>; }
function LoadingPage() { return <Shell eyebrow="加载中" title="正在准备工作台"><section className="panel"><p className="muted">正在读取本地 Mock 数据…</p></section></Shell>; }
